### ISSUE TITLE
Model comparison missing section

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/Exploratory-Analysis-of-Bayesian-Models#14]
plot_compare, WAIC. Bayes Factor

**Comment by OriolAbril** [comment]
i think we should use this section to explain how to handle multiple observations and ic calculation for hierarchical models (i.e. similarly to these two discourse answers: [one](https://discourse.pymc.io/t/calculating-waic-for-models-with-multiple-likelihood-functions/4834/5?u=oriolabril), [two](https://discourse.pymc.io/t/modeling-human-response-time-data-with-an-exponential-model-model-comparison-issues/3666/9?u=oriolabril)). 

ArviZ docs on `waic`, `loo` and `compare` should then add this to `See also`/`References` section. Eventually, that would close https://github.com/arviz-devs/arviz/issues/987 and https://github.com/arviz-devs/arviz/issues/998.

Does the rugby model sound as a good example for this? I don't like that leave one match out is so similar to leave _half match/goal recording_ out. A couple options are to use football league data (premier or spanish league have 20 teams instead of 8, but still not sure would work) or using a similar model but on some other field where the equivalent to match has 3 or 4 components instead of only 2.

**Comment by AlexAndorra** [comment]
Good idea!
Working on a football model would be fun 😉 Are there some good data available though?
We can also write a first version with the rugby model (highlighting that the two different CVs are _not_ expected to always be the same), and update with a new, better football example later?

**Comment by OriolAbril** [comment]
> Are there some good data available though?

It is easy to copy from wikipedia :wink: and do some pandas magic.

**Comment by canyon289** [comment]
I support everything said here

**Comment by aloctavodia** [comment]
We should also include an explanation on the different methods of computing model's weights (mostly stacking vs pseudo-BMA) and more important the effects this have on the expected results. See https://github.com/arviz-devs/arviz/issues/2077 for a common misconception we need to address
